### PR TITLE
fix: replit issues

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Related to https://github.com/freeCodeCamp/freeCodeCamp/issues/46910

### CODE REVIEW

**Review by RandellDawson — CHANGES_REQUESTED** [review]
See [my comments](https://github.com/freeCodeCamp/freeCodeCamp/pull/47050#issuecomment-1200248050) regarding why we need to get `/learn` updated to reflect users will see an error for the first challenge in Advanced Node.

**Comment by RandellDawson** [comment]
@scissorsneedfoodtoo I created https://github.com/freeCodeCamp/freeCodeCamp/pull/47108 with changes in the instructions so that if you make the following change in the `server.js` file, the user will not see any error messages when first starting up the app due to adding `pug` to `package.json` and already having `res.render()` in the boilerplate.

Change:
```js
app.route('/').get((req, res) => {
  res.render('Load your view here');
});
```
to:
```js
app.route('/').get((req, res) => {

});
```

**Comment by scissorsneedfoodtoo** [comment]
Awesome, thanks for pointing this out @RandellDawson. It would be great to get your suggested change here to make those improvements in https://github.com/freeCodeCamp/freeCodeCamp/pull/47108.

I'll go ahead and update this PR now. I'll also add a note / tag in https://github.com/freeCodeCamp/freeCodeCamp/pull/47108 that the changes for this boilerplate should be reviewed and merged first, before the updates to Learn.

Edit: @RandellDawson, this should be ready for another round of reviews.

**Review by Sboonny — APPROVED** [review]

**Comment by Sboonny** [comment]
LGTM 🎉, thank you for your contribution to the page! 👍.

**Pull request merged**
